name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.3
  equatable: ^2.0.3

  json_annotation: ^4.8.1
  freezed_annotation: ^2.1.0

  # Network client
  dio: ^5.3.2
  retrofit: ^4.0.1

  shimmer: ^3.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  retrofit_generator:
  build_runner: ^2.4.4
  json_serializable: ^6.5.4
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
